### ISSUE TITLE
Add project links UX issue

### ISSUE THREAD

**Issue by khadeejasattar26** [sheharyarn/cloudup.dev#23]
Add project links with read me and homepage of github.

**Comment by ahmadzahiddd** [comment]
What I Liked:

Recognizing the importance of addressing UX issues, specifically regarding project links.
Suggestions/Concerns:

Clearly define the expected behavior when users interact with project links to set consistent user expectations.
Ensure that the added links are accessible and provide relevant information to enhance the user experience.
Consider conducting user testing to gather feedback on the proposed changes and ensure they meet user needs.
Collaborate with designers or UX experts to incorporate best practices for optimal user interaction.
Reproducible Steps (if applicable):

Provide examples or scenarios where users might encounter project links and how the proposed changes would improve their experience.
Additional Context:

Test the proposed changes on different devices and screen sizes to ensure responsiveness.
Encourage feedback from end-users or stakeholders to gauge the impact of the proposed UX improvements.
Gratitude:

Thank you for prioritizing UX enhancements. Improving the user interface will contribute significantly to a positive user experience.

**Comment by sheharyarn** [comment]
Project links are already added to the Github, and the Github link is already added to the project webpage.

If I'm misunderstanding, please clarify.
